stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - data/Telco_Churn.csv
      - src/preprocess.py
    outs:
      - data/processed.csv

  train:
    cmd: python src/train_model.py
    deps:
      - data/processed.csv
      - src/train_model.py
    outs:
      - models/model.pkl
      - models/label_encoders.pkl
      - models/scaler.pkl

  report:
    cmd: python src/generate_report.py
    deps:
      - models/model.pkl
      - src/generate_report.py
    outs:
      - reports/report.html